### ISSUE TITLE
Ready indicator for orders containing duplicate potions

### ISSUE THREAD

**Issue by RonnyTommy548** [hex-agon/mastering-mixology#50] opened 2024-10-05 15:58 UTC
This was my order:
![image](https://github.com/user-attachments/assets/6ce2fd2a-102b-4dca-9a3a-292ed4b0c4b9)
And I created 2 MMA crystallised potions, but only the top one is showing ready. It doesn't seem to mark the other as ready when u create an additional one.

**Comment by hex-agon** [comment] 2024-10-05 16:09
duplicate of https://github.com/hex-agon/mastering-mixology/issues/43

**Comment by hex-agon** [comment] 2024-10-05 16:52
Fixed with 4f3262b794b61967d98a19deb34d738e97347eb4

**Closed by hex-agon** 2024-10-05 16:52 UTC
