### ISSUE TITLE
1.4.0 "ready!" indicator is staying in the potion ID spot after turn in

### ISSUE THREAD

**Issue by rjellis7** [hex-agon/mastering-mixology#49] opened 2024-10-05 15:42 UTC
With the new 1.4.0 update, the "ready!" indicator stays in the HUD potion ID spot even after turning in the potion. It makes brain operation on deciding which lever to pull first while running back to the start much easier when the potion ID is ready after turning in a potion.

**Comment by artypoop** [comment] 2024-10-05 16:01
Please add a toggle for this "ready" UI feature. I don't think it's needed :(

**Comment by hex-agon** [comment] 2024-10-05 16:09
duplicate of https://github.com/hex-agon/mastering-mixology/issues/43

**Comment by rjellis7** [comment] 2024-10-05 16:17
I see the link and the discussion now so my bad. I checked the open issues list before I posted it and #43 specifically isn't showing there for some reason.. My bad!

**Closed** 2024-10-05 16:28 UTC
