### ISSUE TITLE
"ready!" label stays after depositing until you hit a lever

### ISSUE THREAD

**Issue by Ribel38** [hex-agon/mastering-mixology#46] opened 2024-10-05 14:29 UTC
"ready!" label stays after depositing, which hides the formula of the new orders until you hit a lever.

Optimally it would be nice if it went away on depositing, but if it's not possible, I'd rather be able to see easily see the formulas after depositing than having it. Maybe it could be an option in the settings?  

Thanks

**Comment by raiyni** [comment] 2024-10-05 14:38
duplicate of https://github.com/hex-agon/mastering-mixology/issues/43

**Closed by raiyni** 2024-10-05 14:38 UTC
